### ISSUE TITLE
bug - hide creature name toggle not working

### ISSUE THREAD

**Issue by ditzer252** [reonZ/mini-tracker#33]
Creatures with hidden names are listed and dimmed as expected, but clicking the toggle does not hide/unhide names.
No other mods installed, just using the base PF2e setting for "Tokens determine NPC name visibility."

FVTT v 11.315
PF2e v 5.10.5
Mini Tracker v 1.20.1

**Comment by reonZ** [comment]
the oversight is actually the tooltip shown, the module doesn't allow toggling of name visibility when using the pf2e metagame, because it entirely depends on the token's nameplate state, which can be more that 2 options (it is not just on/off).

`Mini Tracker` was actually meant to be used with another of my modules `Anonymous` which takes care of it all, i still decided to show the visibility state when using pf2e metagame for convenience but i guess i forgot to make it clear with the tooltip

to be honest, i don't think many people in the pf2e community use it, so i never got any feedback and my group use `Anonymous` instead of the pf2e metagame.
