### ISSUE TITLE
feature request - scale token images with popout effects

### ISSUE THREAD

**Issue by ditzer252** [reonZ/mini-tracker#35]
Would it be possible to adjust size of tokens according to the scale of the tokens on the canvas?  Right now, tokens that have pop-out effects (e.g., PF2e Bestiary Tokens) appear smaller in the mini-tracker.   Thank you.

**Comment by reonZ** [comment]
I am pretty sure i did something about it at some point.

**Comment by reonZ** [comment]
ok after checking, i definitely did something about it but never actually commit the work...

![image](https://github.com/reonZ/mini-tracker/assets/651462/c3a1ab75-0082-4b86-883a-a967e8eeacca)

it has been sitting there for more than 2 months now, at least i am not crazy.

i haven't tested much because i don't have access to the bestiary module (my GM is the one who bought it) so this is probably gonna have some weird results.
