### ISSUE TITLE
Enhancement request:

### ISSUE THREAD

**Issue by dstein766** [reonZ/mini-tracker#4]
Turns out this is one of those modules I didn't know I was missing until it showed up and I wondered how I survived without it!

Can the "expand up/down" behavior be unlinked from the "swap header/footer" behavior?  I want my mini tracker at the bottom of the screen (and therefore need it to expand UP), but doing this forces me to also accept the swapping of the header and footer bars.  I'd like the latter to mimic standard behavior (i.e. "Not started" + roll/reset icons always at the top, "Begin combat" + next player/round buttons always at the bottom - but this currently isn't supported.

Perhaps the square box that toggles between the two states could instead toggle between 4 states??  e.g.
a) Expands down, header = "Not started"
b) Expands down, header = "Begin combat"
c) Expands up, header = "Not started"
d) Expands up, header = "Begin combat"

This way you wouldn't have to add any further controls.

**Comment by reonZ** [comment]
So you basically want a way to expand upward without changing the UI.

I will see what i can do.

**Comment by reonZ** [comment]
The problem i see with that is that there will be no way to tell which way the tracker actually expands.

**Comment by reonZ** [comment]
After reviewing the thing, i don't think i can make it work seamlessly.

Adding this option would mess with the whole dragging and the resize, since the header will not be opposite to where the window should shrink.

All i can offer you is a "hidden" feature which i have added in the version `1.6.3`. To change this setting, simply open your browser devtools (F12) and in the console type:

    game.settings.set('mini-tracker', 'fake-reversed', true)

To return to the normal behavior simply type:

    game.settings.set('mini-tracker', 'fake-reversed', false)

This will give you what you want without me having to monkey patch the whole module.

Sorry again.
