### ISSUE TITLE
Combat Tracker doesn't show up [PF2e]

### ISSUE THREAD

**Issue by juan-r-apolinario** [reonZ/mini-tracker#9]
I'm using mini-tracker 1.10.0, in PF2e 4.4.2 and Foundry 10.288.

Even without any other modules, the combat tracker doesn't came up to me. I add actors, roll initiative, I start the combat and the only tracker I can see is the Foundry's native one.

When I'm using D&D5e your tracker shows up as soon as I add actors to the initiative order, and your tracker works flawlessly in there.

I'm doing something wrong? The tracker works differently in PF2e?

**Comment by reonZ** [comment]
I just finished playing a PF2e session 40 min ago and the tracker was working. I don't know of a reason it wouldn't work, the only difference is that we are playing on 10.291

![image](https://user-images.githubusercontent.com/651462/206314100-f540b2aa-fb28-49fc-b507-54af01d02e71.png)

- could you check if you have any error in the console.
- could you check if the element `<div id="mini-tracker"` exist in your devtools
- and sorry to put it there, i know this question can be infuriating but can you check if you enabled the tracker in the setting

**Comment by juan-r-apolinario** [comment]
![image](https://user-images.githubusercontent.com/8976433/206593956-2f4f4233-f803-4c9f-8620-4fc364bee73c.png)
Those are the errors in the console.

![image](https://user-images.githubusercontent.com/8976433/206594504-8988eb56-32db-4d44-9d27-ed34441b655c.png)
I did a Ctrl+F in the Elements tab and I found no `<div id="mini-tracker"`. I only found `<div id="lvk-mini-tracker"`.

![image](https://user-images.githubusercontent.com/8976433/206593748-007a4de9-04ad-472a-b1bf-169d18c904c1.png)
Everything other than that isn't activated.

**Comment by reonZ** [comment]
Everything seem in order, but that error is not ok.

That function `ui.combat._getCombatantThumbnail` is core to the foundry, the fact that it tells you that it is not a function is very disturbing because it means that you don't have a combat tracker in your UI, and i don't mean my mini-tracker, but the regular one in the sidebar.

Which is obviously not possible, because my mini-tracker is directly hooked to it.

Could you poke me on the foundry or pf2e discord please ? i don't think we gonna fix that via github messages: `Idle#3251`

**Comment by reonZ** [comment]
I am closing this since you have not given any news.
